linters:
  enable:
    - depguard
    - errcheck

linters-settings:
  depguard:
    rules:
      rand: 
        files:
          - "**/*.go"
        deny:
          - pkg: "math/rand"
            desc: use `math/rand/v2` instead
  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true

